#pragma once
#include <iostream>
#include <cstdio>
#include <utility>
#include <string>
#include <vector>
#include <memory>
#include <algorithm>
#include <ranges>
#include <format>
#include <print>
#include <cmath>
#include <limits>
#include <random>
#include <fstream>
#include <filesystem>
#include <type_traits>
#include <map>
#include <sstream>
#include <stdexcept>